name: sneakers_app
description: A Sneakers App - Flutter


publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  font_awesome_flutter: ^10.4.0
  custom_navigation_bar: ^0.8.2
  simple_animations: ^4.0.1
  supercharged: ^2.1.1
  shared_preferences: ^2.0.15


  cloud_firestore: ^4.8.1
  firebase_auth: ^4.6.3
  firebase_core: ^2.14.0

  syncfusion_flutter_charts: ^20.1.58	
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  intl: ^0.18.1  

  geolocator: ^9.0.2
  http: ^0.13.6
  flutter_spinkit: ^5.2.0
  path_provider: ^2.0.15

dependency_overrides:
  firebase_core_platform_interface: ^4.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

  hive_generator: ^2.0.0
  build_runner: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - images/   
       

  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-Regular.ttf
        - asset: assets/fonts/OpenSans-Bold.ttf
          weight: 700
    - family: Quicksand
      fonts:
        - asset: assets/fonts/Quicksand-Regular.ttf
        - asset: assets/fonts/Quicksand-Bold.ttf
          weight: 700

    - family: 's'
      fonts:
        - asset: fonts/Roboto-Regular.ttf    
